export const FETCH_START = "FETCH_PROJECTS_SUCCESS";
export const FETCH_SUCCESS = "FETCH_PROJECTS_ERROR";
export const FETCH_ERROR = "FETCH_ERROR";
export const ACCOUNT_TYPE_MODAL = "ACCOUNT_TYPE_MODAL";
export const IS_HOME_PAGE = "IS_HOME_PAGE";

export const PROJECT_FETCH_START = "PROJECT_FETCH_START";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_ERROR = "PROJECT_FETCH_ERROR";

export const DETAILS_PROJECT_FETCH_START = "DETAILS_PROJECT_FETCH_START";
export const DETAILS_PROJECT_FETCH_SUCCESS = "DETAILS_PROJECT_FETCH_SUCCESS";
export const DETAILS_PROJECT_FETCH_ERROR = "DETAILS_PROJECT_FETCH_ERROR";

export const LANGUAGE_DITACTOR = "LANGUAGE_DITACTOR";

export const FETCH_ABOUT_US_START = "FETCH_ABOUT_US_START";
export const FETCH_ABOUT_US_SUCCESS = "FETCH_ABOUT_US_SUCCESS";
export const FETCH_ABOUT_US_ERROR = "FETCH_ABOUT_US_ERROR";

export const FETCH_PRIVACY_POLICY_START = "FETCH_PRIVACY_POLICY_START";
export const FETCH_PRIVACY_POLICY_SUCCESS = "FETCH_PRIVACY_POLICY_SUCCESS";
export const FETCH_PRIVACY_POLICY_ERROR = "FETCH_PRIVACY_POLICY_ERROR";

export const FETCH_EXPERT_PROJECT_START = "FETCH_EXPERT_PROJECT_START";
export const FETCH_EXPERT_PROJECT_SUCCESS = "FETCH_EXPERT_PROJECT_SUCCESS";
export const FETCH_EXPERT_PROJECT_ERROR = "FETCH_EXPERT_PROJECT_ERROR";

export const FETCH_PARTNERS_START = "FETCH_PARTNERS_START";
export const FETCH_PARTNERS_SUCCESS = "FETCH_PARTNERS_SUCCESS";
export const FETCH_PARTNERS_ERROR = "FETCH_PARTNERS_ERROR";

export const IS_DONATE_MODAL = "IS_DONATE_MODAL";

export const GET_USER = "GET_USER";

export const FETCH_REGISTER_DATA_START = "FETCH_REGISTER_DATA_START";
export const FETCH_REGISTER_DATA_SUCCESS = "FETCH_REGISTER_DATA_SUCCESS";
export const FETCH_REGISTER_DATA_ERROR = "FETCH_REGISTER_DATA_ERROR";

export const RECOMMENTED_MODAL_OPEN = "RECOMMENTED_MODAL_OPEN";
export const OPEN_DONATE_SINGLE_PROJECT = "OPEN_DONATE_SINGLE_PROJECT";
export const CONGRATS_MODAL = "CONGRATS_MODAL";

export const OPEN_PRIVACY_POLICY = "OPEN_PRIVACY_POLICY";
export const MODAL_NAME = "MODAL_NAME";
export const AGREEMENT_TERMS = "AGREEMENT_TERMS";

// export const GMAIL_LOGIN_START = "GMAIL_LOGIN_START";
// export const GMAIL_LOGIN_SUCCESS = "GMAIL_LOGIN_SUCCESS";
// export const GMAIL_LOGIN_ERROR = "GMAIL_LOGIN_ERROR";

// export const FACEBOOK_LOGIN_START = "FACEBOOK_LOGIN_START";
// export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
// export const FACEBOOK_LOGIN_ERROR = "FACEBOOK_LOGIN_ERROR";

export const SOCIAL_MEDIAS_LOGIN_START = "SOCIAL_MEDIAS_LOGIN_START";
export const SOCIAL_MEDIAS_LOGIN_SUCCESS = "SOCIAL_MEDIAS_LOGIN_SUCCESS";
export const SOCIAL_MEDIAS_LOGIN_ERROR = "SOCIAL_MEDIAS_LOGIN_ERROR";

export const GMAIL_LOGIN_CALLBACK_START = "GMAIL_LOGIN_CALLBACK_START";
export const GMAIL_LOGIN_CALLBACK_SUCCESS = "GMAIL_LOGIN_CALLBACK_SUCCESS";
export const GMAIL_LOGIN_CALLBACK_ERROR = "GMAIL_LOGIN_CALLBACK_ERROR";

export const FACEBOOK_LOGIN_CALLBACK_START = "FACEBOOK_LOGIN_START";
export const FACEBOOK_LOGIN_CALLBACK_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_CALLBACK_ERROR = "FACEBOOK_LOGIN_ERROR";

export const FETCH_FAVORITE_PROJECTS_START = "FETCH_FAVORITE_PROJECTS_START";
export const FETCH_FAVORITE_PROJECTS_SUCCESS =
  "FETCH_FAVORITE_PROJECTS_SUCCESS";
export const FETCH_FAVORITE_PROJECTS_ERROR = "FETCH_FAVORITE_PROJECTS_ERROR";

export const FETCH_CONTACT_START = "FETCH_CONTACT_START";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_ERROR = "FETCH_CONTACT_ERROR";
