export const FETCH_START = "FETCH_PROJECTS_SUCCESS";
export const FETCH_SUCCESS = "FETCH_PROJECTS_ERROR";
export const FETCH_ERROR = "FETCH_ERROR";
export const ACCOUNT_TYPE_MODAL = "ACCOUNT_TYPE_MODAL";
export const IS_HOME_PAGE = "IS_HOME_PAGE";

export const PROJECT_FETCH_START = "PROJECT_FETCH_START";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_ERROR = "PROJECT_FETCH_ERROR";

export const DETAILS_PROJECT_FETCH_START = "DETAILS_PROJECT_FETCH_START";
export const DETAILS_PROJECT_FETCH_SUCCESS = "DETAILS_PROJECT_FETCH_SUCCESS";
export const DETAILS_PROJECT_FETCH_ERROR = "DETAILS_PROJECT_FETCH_ERROR";

export const LANGUAGE_DITACTOR = "LANGUAGE_DITACTOR";

export const FETCH_ABOUT_US_START = "FETCH_ABOUT_US_START";
export const FETCH_ABOUT_US_SUCCESS = "FETCH_ABOUT_US_SUCCESS";
export const FETCH_ABOUT_US_ERROR = "FETCH_ABOUT_US_ERROR";

export const FETCH_PRIVACY_POLICY_START = "FETCH_PRIVACY_POLICY_START";
export const FETCH_PRIVACY_POLICY_SUCCESS = "FETCH_PRIVACY_POLICY_SUCCESS";
export const FETCH_PRIVACY_POLICY_ERROR = "FETCH_PRIVACY_POLICY_ERROR";

export const FETCH_EXPERT_PROJECT_START = "FETCH_EXPERT_PROJECT_START";
export const FETCH_EXPERT_PROJECT_SUCCESS = "FETCH_EXPERT_PROJECT_SUCCESS";
export const FETCH_EXPERT_PROJECT_ERROR = "FETCH_EXPERT_PROJECT_ERROR";

export const FETCH_PARTNERS_START = "FETCH_PARTNERS_START";
export const FETCH_PARTNERS_SUCCESS = "FETCH_PARTNERS_SUCCESS";
export const FETCH_PARTNERS_ERROR = "FETCH_PARTNERS_ERROR";

export const IS_DONATE_MODAL = "IS_DONATE_MODAL";

export const GET_USER = "GET_USER";

export const FETCH_REGISTER_DATA_START = "FETCH_REGISTER_DATA_START";
export const FETCH_REGISTER_DATA_SUCCESS = "FETCH_REGISTER_DATA_SUCCESS";
export const FETCH_REGISTER_DATA_ERROR = "FETCH_REGISTER_DATA_ERROR";

export const RECOMMENTED_MODAL_OPEN = "RECOMMENTED_MODAL_OPEN";
export const OPEN_DONATE_SINGLE_PROJECT = "OPEN_DONATE_SINGLE_PROJECT";
export const CONGRATS_MODAL = "CONGRATS_MODAL";

export const OPEN_PRIVACY_POLICY = "OPEN_PRIVACY_POLICY";
export const MODAL_NAME = "MODAL_NAME";
export const AGREEMENT_TERMS = "AGREEMENT_TERMS";