export const FETCH_START = "FETCH_PROJECTS_SUCCESS";
export const FETCH_SUCCESS = "FETCH_PROJECTS_ERROR";
export const FETCH_ERROR = "FETCH_ERROR";

export const PROJECT_FETCH_START = "PROJECT_FETCH_START";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_ERROR = "PROJECT_FETCH_ERROR";

export const DETAILS_PROJECT_FETCH_START = "DETAILS_PROJECT_FETCH_START";
export const DETAILS_PROJECT_FETCH_SUCCESS = "DETAILS_PROJECT_FETCH_SUCCESS";
export const DETAIL_PROJECT_FETCH_ERROR = "DETAIL_PROJECT_FETCH_ERROR";

export const LANGUAGE_DITACTOR = "LANGUAGE_DITACTOR";

export const FETCH_ABOUT_US_START = "FETCH_ABOUT_US_START";
export const FETCH_ABOUT_US_SUCCESS = "FETCH_ABOUT_US_SUCCESS";
export const FETCH_ABOUT_US_ERROR = "FETCH_ABOUT_US_ERROR";

export const FETCH_PRIVACY_POLICY_START = "FETCH_PRIVACY_POLICY_START";
export const FETCH_PRIVACY_POLICY_SUCCESS = "FETCH_PRIVACY_POLICY_SUCCESS";
export const FETCH_PRIVACY_POLICY_ERROR = "FETCH_PRIVACY_POLICY_ERROR";
